[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
patient_data_chain = "9Yyu16cGeVGso1FjLdSmgCPNSGpGLkPoXgqLfQ8N5zt5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
